import Head from "next/head";
import { ReactNode } from "react";
import { LayoutProps } from "./PageWithLayout";

interface Props {
  children: ReactNode;
}

const AdminLayout: LayoutProps = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/primeicons/primeicons.css"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/primereact/resources/themes/lara-light-indigo/theme.css"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/primereact/resources/primereact.min.css"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/primeflex@2.0.0/primeflex.min.css"
        />
      </Head>
      <div>{children}</div>
    </>
  );
};

export default AdminLayout;
