import Head from "next/head";
import { ReactNode } from "react";
import { LayoutProps } from "./PageWithLayout";

interface Props {
  children: ReactNode;
}

const AdminLayout: LayoutProps = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{children}</div>
    </>
  );
};

export default AdminLayout;
