import Navbar from "../Navbar";
import { ReactNode } from "react";
import { LayoutProps } from "./PageWithLayout";
import Footer from "../footer";
import Head from "next/head";

interface Props {
  children: ReactNode;
}

const Layout: LayoutProps = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Ifrats Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
